/*
 * Aquì va el objeto con los colores que van en la versión dark
 * */

import COLORS from './colors';
export default {
  authBackgroundColor: COLORS.black,
  authButton: COLORS.black,
  authButtonText: COLORS.white,
  backGroundDrawer: COLORS.hardBlue,
  backGroundAna: COLORS.hardBlueSecondary,
  backGroundScreen: COLORS.hardBlue,
  bottomGradient: COLORS.hardBlue,
  bottomTabActive: COLORS.primary,
  bottomTabInactive: COLORS.hardBlueSecondary,
  bubbleIn: COLORS.semiBlue,
  bubbleInText: COLORS.white,
  bubbleOut: COLORS.hardPrimary,
  bubbleOutText: COLORS.white,
  cardBackground: COLORS.hardBlueSecondary,
  careDescription: COLORS.white,
  careTitle: COLORS.primary,
  h1: COLORS.primary,
  h1Auth: COLORS.primary,
  headerText: COLORS.white,
  headerTextAna: COLORS.white,
  loadingMessage: COLORS.white,
  mainText: COLORS.white,
  p: COLORS.grey,
  pagerSelected: COLORS.primary,
  pagerUnselected: COLORS.softGrey,
  primary: COLORS.primary,
  primaryButton: COLORS.white,
  primaryButtonText: COLORS.black,
  secondaryButton: COLORS.primary,
  secondaryButtonText: COLORS.black,
  topAna: COLORS.black,
  topGradient: COLORS.black,
  topTabBack: COLORS.hardGrey,
  topTabBackActive: COLORS.primary,
  topTabTint: COLORS.black,
  topTabTintActive: COLORS.black,
};
