import {useHTTP} from '../../hooks';
import {ActionCreator} from 'redux';
import {getTest} from '../actions/care';
import {asyncLogout} from './auth';
const response = {
  code: 200,
  message: 'Ok',
  success: true,
  data: {
    questions: [
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610b1940677fcd4ff0d5',
        name: 'Encuesta Care (CONNECT) P1',
        description:
          '1.Practico la gratitud resaltando las cosas buenas que me pasan durante el día.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610b1940677fcd4ff0d6',
        name: 'Encuesta Care (CONNECT) P2',
        description:
          '2.Expreso mi agradecimiento a las personas que contribuyen positivamente en mi vida.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610c1940677fcd4ff0d7',
        name: 'Encuesta Care (CONNECT) P3',
        description:
          '3.Cuento con el apoyo de familiares/ amigos cuando lo necesito',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610c1940677fcd4ff0d8',
        name: 'Encuesta Care (CONNECT) P4',
        description:
          '4.Puedo reconocer y nombrar las emociones que experimento',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610c1940677fcd4ff0d9',
        name: 'Encuesta Care (CONNECT) P5',
        description: '5.Fácilmente pierdo el control de mis emociones.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610c1940677fcd4ff0da',
        name: 'Encuesta Care (CONNECT) P6',
        description:
          '6.Guardo mis aparatos electrónicos o los pongo en modo silencio cuando paso tiempo con mis seres queridos.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610c1940677fcd4ff0db',
        name: 'Encuesta Care (CONNECT) P7',
        description:
          '7.Me siento satisfecho con mis relaciones interpersonales',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0dc',
        name: 'Encuesta Care (CONNECT) P8',
        description: '8.¿Cuántas horas al día socializo con otras personas?',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 1,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0dd',
        name: 'Encuesta Care (ACTIVATE) P1',
        description:
          '1.Procuro mantenerme físicamente activo(a) a lo largo del día (Ejemplo: uso las escaleras en lugar del elevador, me levanto a caminar por lo menos cada 90 minutos en el trabajo, etc).',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 2,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0de',
        name: 'Encuesta Care (ACTIVATE) P2',
        description: '2.En promedio, ¿cuántas horas permanezco sentado al día',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 2,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0df',
        name: 'Encuesta Care (ACTIVATE) P3',
        description:
          '3.Realizo ejercicio de intensidad moderada (que implica una ligera aceleración de la respiración y el ritmo cardiaco) durante mínimo 20 minutos consecutivos por lo menos 3 veces por semana.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 2,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0e0',
        name: 'Encuesta Care (ACTIVATE) P4',
        description:
          '4.Me cuesta recuperar la respiración al realizar actividades físicas como caminar o subir las escaleras.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 2,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610d1940677fcd4ff0e1',
        name: 'Encuesta Care (RELAX) P1',
        description:
          '1.¿Cuántas horas a la semana dedico tiempo a realizar actividades recreativas (ej: ir al cine, salir al parque, jugar juegos de mesa, etc)?',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610e1940677fcd4ff0e2',
        name: 'Encuesta Care (RELAX) P2',
        description:
          '2.Organizo mi tiempo para realizar mis actividades diarias.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610e1940677fcd4ff0e3',
        name: 'Encuesta Care (RELAX) P3',
        description: '3.Balanceo mi tiempo personal, de familia y de trabajo.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610e1940677fcd4ff0e4',
        name: 'Encuesta Care (RELAX) P4',
        description: '4.En promedio, ¿cuántas horas duermo al día?',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610e1940677fcd4ff0e5',
        name: 'Encuesta Care (RELAX) P5',
        description: '5.Durante el día me siento cansado y con sueño.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610e1940677fcd4ff0e6',
        name: 'Encuesta Care (RELAX) P6',
        description:
          '6.Practico ejercicios de mindfulness (atención plena), meditación o respiración por lo menos 5 veces por semana',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 3,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0e7',
        name: 'Encuesta Care (EAT) P1',
        description: '1.Siento sueño o cansancio después de comer.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0e8',
        name: 'Encuesta Care (EAT) P2',
        description:
          '2.Con frecuencia, siento molestias estomacales o inflamación',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0e9',
        name: 'Encuesta Care (EAT) P3',
        description:
          '3.Consumo más de 3 alimentos ultraprocesados (ej: alimentos que incluyan harina refinada, azúcar refinada, lista de ingredientes no naturales) al día.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0ea',
        name: 'Encuesta Care (EAT) P4',
        description: '4.Mi plato se conforma de verduras en un 50%.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0eb',
        name: 'Encuesta Care (EAT) P5',
        description: '5.Bebo entre 6 y 8 vasos de agua al día.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e610f1940677fcd4ff0ec',
        name: 'Encuesta Care (EAT) P6',
        description:
          '6.¿Con qué frecuencia bebo refrescos o bebidas endulzadas?',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
      {
        answers: [
          {
            _id: '5f4d4c319d0ee068bc75d373',
            text: '1',
            description: 'rango',
            value: 1,
            unit_points: 1,
          },
          {
            _id: '5f4d4c509d0ee068bc75d374',
            text: '2',
            description: 'rango',
            value: 2,
            unit_points: 2,
          },
          {
            _id: '5f4d4c5e9d0ee068bc75d375',
            text: '3',
            description: 'rango',
            value: 3,
            unit_points: 3,
          },
          {
            _id: '5f4d4c6d9d0ee068bc75d376',
            text: '4',
            description: 'rango',
            value: 4,
            unit_points: 4,
          },
          {
            _id: '5f4d4c849d0ee068bc75d377',
            text: '5',
            description: 'rango',
            value: 5,
            unit_points: 5,
          },
        ],
        _id: '5f4e61101940677fcd4ff0ed',
        name: 'Encuesta Care (EAT) P7',
        description: '7.Me doy cuenta cuando como en exceso.',
        question_type: {
          _id: '5f4d395033097e637f5ce652',
          name: 'Rango(1-5)',
          key: 3,
          order: 3,
          has_file: false,
        },
        group: 4,
      },
    ],
    evalue_by_group: true,
    get_percents: true,
    level: 0,
    is_recursive: false,
    recursive_days: [],
    retry: 0,
    include_in_pool: true,
    iso_language_code: 'es_MX',
    _id: '5f4e61101940677fcd4ff0ee',
    createdAt: '2020-09-01T14:49:33.000Z',
    updatedAt: '2020-09-01T14:49:33.000Z',
    name: 'Encuesta care',
    description:
      'La encuesta care sirve para determinar el pilar donde se establece la habilidad con que trabajara el usuario',
    instructions:
      'Responda correctamente las siguientes preguntas de acuerdo a su persona',
    kind_of_activity: {
      question_types: [
        '5f4d36fd5175f56333b3bd94',
        '5f4d395033097e637f5ce652',
        '5f4e69c81940677fcd4ff0f5',
        '5f4e69fe1940677fcd4ff0f6',
      ],
      iso_language_code: 'es_MX',
      _id: '5f4d34fcecc26862ab706e19',
      createdAt: '2020-08-31T17:33:29.000Z',
      updatedAt: '2020-09-09T14:23:00.000Z',
      name: 'Encuesta',
      description: 'Con este tipo de elemento se crearan las encuestas ',
      key: 1,
      order: 1,
      createdBy: '5f3305510c9df608e0e37279',
      __v: 0,
    },
    points: 0,
    is_global: true,
    createdBy: '5f3305510c9df608e0e37279',
    __v: 0,
  },
  i18n: 'ok',
  global: {
    es_MX: 'Exitoso!',
    pt_BR: 'Bem sucedido!',
    en_US: 'Success!',
  },
};
export function asyncGetTest() {
  return async (dispatch: ActionCreator<any>) => {
    //const response = await useHTTP('GET', 'api/survey/one/?where[name]=Encuesta care')
    if (response.code === 403) {
      asyncLogout();
    } else {
      dispatch(getTest(response.data.name, response.data.questions));
    }
  };
}
